`KeyedVector` removed in Gensim 4.0.0.
AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.

> Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.